### ISSUE TITLE
LE scan test throws Exception in thread HCISocketPoller

### ISSUE THREAD

**Issue by iiSeymour** [TheBubbleworks/python-hcipy#2]
Using the example snippet from the README.md with `le_scan_test.py` results in just the device information being printed followed by an exception being raised.

```python
ble_scan_test = BluetoothLEScanTest()
ble_scan_test.set_scan_enable(False)
ble_scan_test.set_filter()
ble_scan_test.set_scan_parameters()
ble_scan_test.set_scan_enable(True, True)
```

> Exception in thread HCISocketPoller (most likely raised during interpreter shutdown)

I think this is due to the interpreter exiting but the `socket_poll_thread` not getting cleaned up.

**Comment by WayneKeenan** [comment]
Thanks again for your patch, but this experiment is over and development has moved to https://github.com/TheCellule/python-bleson
