### ISSUE TITLE
Advertisement test operator priority issues

### ISSUE THREAD

**Issue by iiSeymour** [TheBubbleworks/python-hcipy#4]
The [shifting operations](https://docs.python.org/3/reference/expressions.html#shifting-operations) have lower priority than the arithmetic operations in Python and in the `le_advertisement_test.py` example there are many cases of `a<<n + b` *(which are getting interpreted as `(a+b)<<n`)* that I believe should be `(a<<n) + b`.

**Comment by WayneKeenan** [comment]
Thanks for your patches. 
This module is no longer being actively developed, and focus has shifted to https://github.com/TheCellule/python-bleson
